image_search_paths:
  # Directories to search for images when loading files, automatically starts with the same directory as the config file
  - ./Leveled/Tileset/004
  - //storage2.connectomes.utah.edu/Data/Volumes/MiniRC1x/
replacement_paths:
  \\OpR-Marc-Syn1\\: \\storage1.connectomes.utah.edu\\Data\\
  \\Opr-Marc-Syn2\\: \\storage2.connectomes.utah.edu\\Data\\
  \\Opr-Marc-Syn3\\: \\storage3.connectomes.utah.edu\\Data\\
  \\Opr-Marc-Syn4\\: \\storage4.connectomes.utah.edu\\Data\\


control_point_search_radius: 10
max_zoom: 16
min_zoom: 0.00390625
debug: True
readme_file: README.txt
alignment_tile_size: 128
alignment_max_search_angle: 15
alignment_search_angle_step: 3
